steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-f', 'Dockerfile.jfr', '-t', 'jenkinsfile-runner', '.' ]
- name: jenkinsfile-runner
  entrypoint: 'bash'
  args:
  - '-c'
  - |
      mkdir -p /workspace/tmp
      /app/bin/jenkinsfile-runner --runHome /workspace/tmp -f /workspace
